version: '2.2'
services:
  api:
    build: 
      context: ./FloogleAPI/
      dockerfile: Dockerfile
      args:
        uid: 1000
    image: floogleapi:latest
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    env_file: "./FloogleAPI/.env.staging"
    ports: 
      - "8081:80"
    volumes: 
      - ./FloogleAPI:/var/www/html
    networks:
      - flooglenet
  web:
    build:
      context: ./FloogleWeb/
      dockerfile: Dockerfile-prod
    image: floogleweb:latest
    volumes:
      - './FloogleWeb:/app'
      - '/app/node_modules'
    ports:
      - "8080:80"
    networks:
      - flooglenet

  crawler:
    build:
      context: ./WebCrawler/
      dockerfile: Dockerfile
    image: webcrawler:latest
    env_file:
      "./WebCrawler/.env.staging"
    command:
      - /root/crawl.sh
    networks:
      - flooglenet
  
  reverseproxy:
    build:
      context: ./Nginx/
      dockerfile: Dockerfile
    image: reverseproxy:latest
    networks:
      - flooglenet
    ports:
      - 80:80
      - 433:433


networks:
  flooglenet:
